#!/usr/bin/env bash
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UI_DIR="$REPO_ROOT/ui"
ENV_FILE="$REPO_ROOT/.env"
PORT=${1:-8080}

# Load .env and generate ui/config.js.
if [ -f "$ENV_FILE" ]; then
    while IFS='=' read -r key value; do
        [[ "$key" =~ ^#|^$ ]] && continue
        case "$key" in
            API_URL|API_KEY|POSTGREST_URL|SUPABASE_URL|SUPABASE_KEY) export "$key=${value//\"/}" ;;
        esac
    done < "$ENV_FILE"
fi

API_URL="${API_URL:-${POSTGREST_URL:-${SUPABASE_URL:-http://localhost:8787}}}"
API_KEY="${API_KEY:-${SUPABASE_KEY:-}}"

cat > "$UI_DIR/config.js" <<EOF
// Generated by serve_ui.sh — do not edit by hand.
window.API_URL = '$API_URL'
window.API_KEY = '$API_KEY'
EOF

echo "Wrote ui/config.js"
echo "API URL: $API_URL"
echo "Serving UI at http://localhost:${PORT}"
python3 -m http.server "$PORT" --directory "$UI_DIR"
