#!/usr/bin/env bash
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UI_DIR="$REPO_ROOT/ui"
ENV_FILE="$REPO_ROOT/.env"
PORT=${1:-8080}

# Load .env and generate ui/config.js
if [ -f "$ENV_FILE" ]; then
    # Export only the Supabase vars (skip lines that are comments or blank)
    while IFS='=' read -r key value; do
        [[ "$key" =~ ^#|^$ ]] && continue
        case "$key" in
            SUPABASE_URL|SUPABASE_KEY) export "$key=${value//\"/}" ;;
        esac
    done < "$ENV_FILE"
fi

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_KEY" ]; then
    echo "Error: SUPABASE_URL and SUPABASE_KEY must be set in .env or the environment"
    exit 1
fi

cat > "$UI_DIR/config.js" <<EOF
// Generated by serve_ui.sh — do not edit by hand.
window.SUPABASE_URL = '$SUPABASE_URL'
window.SUPABASE_KEY = '$SUPABASE_KEY'
EOF

echo "Wrote ui/config.js"
echo "Serving UI at http://localhost:${PORT}"
python3 -m http.server "$PORT" --directory "$UI_DIR"
